version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"

volumes:
  pg_data: