services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/rails
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      MAILTRAP_USERNAME: ${MAILTRAP_USERNAME}
      MAILTRAP_PASSWORD: ${MAILTRAP_PASSWORD}
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1

  test:
    build: ./backend
    command: bundle exec rspec
    environment:
      RAILS_ENV: test
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: teamtalk_test
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    volumes:
      - ./backend:/rails
    depends_on:
      - db

  sidekiq:
    build: ./backend
    volumes:
      - ./backend:/rails
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
      MAILTRAP_USERNAME: ${MAILTRAP_USERNAME}
      MAILTRAP_PASSWORD: ${MAILTRAP_PASSWORD}
      DATABASE_URL: postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
    command: bundle exec sidekiq

  db:
    image: postgres:15
    restart: always
    # ports:
    #   - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  redis:
    image: redis:7
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

volumes:
  pg_data:
